JavaWeb/book/src/com/atfzr/pojo/Page.java
package com.atfzr.pojo;

import java.util.List;

/**
 * @author silence
 * @date 2022/9/18---9:21
 * @SuppressWarnings({"all"})
 */

/**
 *  Page是分页的模板对象
 * @param <T> 是具体的模块的javaBean类
 */
public class Page<T> {

    public static final Integer PAGE_SIZE = 4;
    //当前页码
    private Integer pageNo;
    //总页码
    private  Integer pageTotal;
    //当前页显示数量
    private  Integer pageSize =  PAGE_SIZE;
    //总记录数
    private  Integer PageTotalCount;
    //当前页数据
    private List<T> items;
    // 分页条的请求地址(为了区分client，manager等等)
    private String url;


    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getPageTotal() {
        return pageTotal;
    }

    public void setPageTotal(Integer pageTotal) {
        this.pageTotal = pageTotal;
    }




    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public Integer getPageTotalCount() {
        return PageTotalCount;
    }

    public void setPageTotalCount(Integer PageTotalCount) {
        this.PageTotalCount = PageTotalCount;
    }

    public Integer getPageNo() {
        return pageNo;
    }

    public void setPageNo(Integer pageNo) {

//        // 数据边界的有效检查
//        if(pageNo < 1){
//            pageNo = 1;
//        }else if(pageNo > pageTotal){
//            pageNo= pageTotal;
//        }

        this.pageNo = pageNo;
    }

    public List<T> getItems() {
        return items;
    }

    public void setItems(List<T> items) {
        this.items = items;
    }

    @Override
    public String toString() {
        return "Page{" +
                "pageNo=" + pageNo +
                ", pageTotal=" + pageTotal +
                ", pageSize=" + pageSize +
                ", PageTotalCount=" + PageTotalCount +
                ", items=" + items +
                ", url='" + url + '\'' +
                '}';
    }
}

JavaWeb/book/web/pages/common/footer.jsp
<%--
  Created by IntelliJ IDEA.
  User: feng'zhi'ren
  Date: 2022/9/15
  Time: 18:58
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div id="bottom">
		<span>
			智仁书城.Copyright &copy;2022
		</span>
</div>

JavaWeb/book/web/pages/common/head.jsp
<%--
  Created by IntelliJ IDEA.
  User: feng'zhi'ren
  Date: 2022/9/15
  Time: 18:50
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    String basePath = request.getScheme()
    + "://"
    + request.getServerName()
    + ":"
    + request.getServerPort()
    + request.getContextPath()
    + "/";
%>
<%--<%=basePath%>--%>

<!--写base标签，永远固定相对路径跳转的结果-->
<base href="<%=basePath%>">

<link type="text/css" rel="stylesheet" href="static/css/style.css">
<script type="text/javascript" src="static/script/jquery-1.7.2.js"></script>

JavaWeb/book/web/pages/common/login_success_menu.jsp
<%--
  Created by IntelliJ IDEA.
  User: feng'zhi'ren
  Date: 2022/9/15
  Time: 18:43
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div>
    <span>欢迎<span class="um_span">${sessionScope.user.username}</span>光临智仁书城</span>
    <a href="pages/order/order.jsp">我的订单</a>
    <a href="userServlet?action=logout">注销</a>&nbsp;&nbsp;
    <a href="index.jsp">返回</a>
</div>

JavaWeb/book/web/pages/common/manager_menu.jsp
<%--
  Created by IntelliJ IDEA.
  User: feng'zhi'ren
  Date: 2022/9/15
  Time: 21:13
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div>
    <%--manager/bookServlet(请求资源的地址)  action=list(调用资源Servlet中的list方法)    --%>
    <%--action=page调用图书分页    --%>
    <a href="manager/bookServlet?action=page">图书管理</a>
    <a href="pages/manager/order_manager.jsp">订单管理</a>
    <a href="index.jsp">返回商城</a>
</div>

JavaWeb/book/web/pages/common/page_nav.jsp
<%--
  Created by IntelliJ IDEA.
  User: feng'zhi'ren
  Date: 2022/9/19
  Time: 9:31
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%--分页条的开始    --%>
<div id="page_nav">
    <%--大于首页，才显示(不然就跳过)--%>
    <c:if test="${requestScope.page.pageNo > 1}">
        <a href="${requestScope.page.url}&pageNo=1">首页</a>
        <a href="${requestScope.page.url}&pageNo=${requestScope.page.pageNo-1}">上一页</a>
    </c:if>

    <%--页码输出的开始--%>
    <c:choose>
        <%--情况 1：如果总页码小于等于 5 的情况，页码的范围是：1-总页码--%>
        <c:when test="${ requestScope.page.pageTotal <= 5 }">
            <c:set var="begin" value="1"/>
            <c:set var="end" value="${requestScope.page.pageTotal}"/>
        </c:when>
        <%--情况 2：总页码大于 5 的情况--%>
        <c:when test="${requestScope.page.pageTotal > 5}">
            <c:choose>
                <%--小情况 1：当前页码为前面 3 个：1，2，3 的情况，页码范围是：1-5.--%> <c:when test="${requestScope.page.pageNo <= 3}">
                <c:set var="begin" value="1"/> <c:set var="end" value="5"/>
            </c:when>
                <%--小情况 2：当前页码为最后 3 个，8，9，10，页码范围是：总页码减 4 - 总页码--%>
                <c:when test="${requestScope.page.pageNo > requestScope.page.pageTotal-3}">
                    <c:set var="begin" value="${requestScope.page.pageTotal-4}"/>
                    <c:set var="end" value="${requestScope.page.pageTotal}"/>
                </c:when>
                <%--小情况 3：4，5，6，7，页码范围是：当前页码减 2 - 当前页码加 2--%> <c:otherwise>
                <c:set var="begin" value="${requestScope.page.pageNo-2}"/>
                <c:set var="end" value="${requestScope.page.pageNo+2}"/>
            </c:otherwise>
            </c:choose>
        </c:when>
    </c:choose>
    <c:forEach begin="${begin}" end="${end}" var="i">
        <c:if test="${i == requestScope.page.pageNo}"> 【${i}】 </c:if>
        <c:if test="${i != requestScope.page.pageNo}">
            <a href="${requestScope.page.url}&pageNo=${i}">${i}</a>
        </c:if>
    </c:forEach>
    <%--页码输出的结束--%>

    <%--        <a href="#">3</a>--%>
    <%--        【${ requestScope.page.pageNo }】--%>
    <%--        <a href="#">5</a>--%>
    <%--小于末页，才显示(不然就跳过)--%>
    <c:if test="${requestScope.page.pageNo <requestScope.page.pageTotal }">
        <a href="${requestScope.page.url}&pageNo=${requestScope.page.pageNo+1}">下一页</a>
        <a href="${requestScope.page.url}&pageNo=${requestScope.page.pageTotal}">末页</a>
    </c:if>
    共${requestScope.page.pageTotal}页，${requestScope.page.pageTotalCount}条记录
    到第<input value="${param.pageNo}" name="pn" id="pn_input"/>页
    <input id="searchPageBtn" type="button" value="确定">


    <script type="text/javascript">

        $(function () {
            // 跳到指定的页码
            $("#searchPageBtn").click(function () {
                var pageNo = $("#pn_input").val();

                // javaScript语言中提供了一个location地址栏对象
                // 它有一个属性叫href，它可以获取浏览器地址栏中的地址
                <%--location.href = "${pageScope.basePath}${requestScope.page.url}&pageNo=" + pageNo;--%>

                <%-- 这里对搜索页码的阈值进行限制，使它不会越界(添加到单击事件)--%>
                if (pageNo < 1 || pageNo > ${requestScope.page.pageTotal}) {
                    alert("请输入正确的页数");
                } else {
                    location.href = "${pageScope.basePath}${requestScope.page.url}&pageNo=" + pageNo;
                }
            });
        });
    </script>

</div>
<%--分页条的结束    --%>